version: '3'
services:
  db:
    image: mafia-family-club/db:0.0.1-SNAPSHOT
    environment:
      - POSTGRES_DB=mafia-family-club
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
  server:
    image: mafia-family-club/server:0.0.1-SNAPSHOT
    depends_on:
          - db
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mafia-family-club
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
  frontend:
    image: mafia-family-club/frontend:0.0.1-SHAPSHOT
    ports:
      - 3000:3000
    expose:
      - 3000