version: '3'
services:
  db:
    build:
      context: ../db
    environment:
      - POSTGRES_DB=mafia-family-club
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
  server:
    build:
      context: ../server
    depends_on:
          - db
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mafia-family-club
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass